apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-server-deployment
  namespace: rust-server-namespace
  labels:
    app: rust-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-server
  template:
    metadata:
      labels:
        app: rust-server
    spec:
      containers:
        - name: rust-server
          image: chethan01/rust-server
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rust-server-service
  namespace: rust-server-namespace
spec:
  selector:
    app: rust-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30000
